#!/bin/bash
set -e

pip install --require-hashes -r requirements.txt --target ./package
rm -rf ./package/cdn_definitions*
pip install --no-deps git+https://${GITHUB_TOKEN}@github.com/release-engineering/cdn-definitions-private.git@master#egg=cdn_definitions_private --target ./package
pip install --no-deps --target ./package .
cp ./configuration/exodus-lambda-deploy.yaml ./package
envsubst < ./configuration/lambda_config.json > ./package/lambda_config.json
aws cloudformation package \
	--template ./package/exodus-lambda-deploy.yaml \
	--s3-bucket $PROJECT-pipeline-artifacts \
	--output-template-file ./package/exodus-lambda-pkg.yaml
